repos:
- repo: https://github.com/bridgecrewio/yor
  rev: 0.1.150
  hooks:
    - id: yor
      name: yor-id
      entry: yor tag -d . --output-json-file result.json
      args: ["."]
      types: [terraform]
      pass_filenames: false