repos:
- repo: https://github.com/bridgecrewio/yor
  rev: 0.1.143
  hooks:
    - id: yor
      name: yor
      entry: yor tag -d 
      args: ["."]
      language: golang
      types: [terraform]
      pass_filenames: false